---
title: "Design principles"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Design principles}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Scope

**Reading** `.npy` and `.npz` files in R.

Writing is out of scope. When working across multiple languages, one should prefer high-performance interoperable format (parquet, zarr, etc.).

# FAQ

## Why not use `reticulate`?

- When reading `.npy` files with `{reticulate}`, at some point in time, two (sometimes 3) copies of the data are made in memory: one in Python and one in R. This can be problematic for large files. With `{grumpy}`, only one copy of the data is made in memory.

## Why is this package slow?

This package is optimized for performance as much as base R allows. We could get better performance by using a lower-level language under the hood, but this package only exist as a crutch if you have received a `.npy` or `.npz` file and want to read it in R.

For better performance when exchanging data across languages, one should prefer high-performance interoperable format (parquet, zarr, etc.).

